# Generated by Django 6.0.5 on 2026-06-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категория'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Категории',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Продукты',
        ),
    ]
